//All Apex codes run on ORG, therefore it should be deployed to Org from VS Code

//call the method of primitiveDataTypeDemo
    //when can we call the class or method?
//creating new instance of class
    //object of the class.

//PrimitiveDataTypeDemo prObj1 = new PrimitiveDataTypeDemo();
//prObj1.printBasicDataType();

PrimitiveDataTypeDemo prObj1 = new PrimitiveDataTypeDemo();
prObj1.printBasicDataType();
